-- WINDOW'S AGGREGATE FUNCTION --

-- 1) MIN()

SELECT EMPLOYEEID, JOBTITLE, SALARY,
MIN(Salary) OVER(PARTITION BY JOBTITLE ORDER BY SALARY) AS MIN_SALARY 
FROM employeesalary 
  
-- 2) MAX()

SELECT EMPLOYEEID, JOBTITLE, SALARY,
MAX(Salary) OVER(PARTITION BY JOBTITLE order by SALARY DESC) AS MAX_SALARY 
FROM employeesalary 

-- 3) AVGERAGE()

SELECT EMPLOYEEID, JOBTITLE, SALARY,
ROUND(AVG(Salary) OVER(PARTITION BY JOBTITLE),0) AS AVG_SALARY 
FROM employeesalary

-- 4) SUM()

SELECT JobTitle, Salary, 
SUM(Salary) OVER(partition by JobTitle) AS TOTAL_SALARY_JOBTITLE_WISE
FROM employeesalary

-- 5) COUNT()

SELECT JobTitle, COUNT(JobTitle) OVER(partition by JobTitle) AS COUNT_JOB_TITLE
FROM employeesalary
ORDER BY COUNT_JOB_TITLE DESC


-- WINDOW'S RANKING FUNCTION --

-- ROW_NUMBER()
-- 1) WITHOUT PARTITION BY

SELECT JobTitle, Salary, 
row_number() OVER(ORDER BY Salary ASC) AS ROW_NO_JOBTITLE_AND_SALARY_WISE
FROM employeesalary

-- 2) WITH PARTITION BY

SELECT JobTitle, Salary, 
row_number() OVER(partition by JobTitle ORDER BY Salary ASC) AS ROW_NO_JOBTITLE_AND_SALARY_WISE
FROM employeesalary

-- RANK()
-- 1) WITHOUT PARTITION BY 

SELECT JOBTITLE, SALARY,
rank() OVER(ORDER BY SALARY DESC) AS RANK_BY_SALARY
FROM employeesalary

-- 2) WITH PARTITION BY 

SELECT JOBTITLE, SALARY,
rank() OVER(PARTITION BY JobTitle ORDER BY SALARY DESC) AS RANK_BY_SALARY
FROM employeesalary

-- DENSE_RANK()
-- 1) WITHOUT PARTITON BY

SELECT JOBTITLE, SALARY,
DENSE_RANK() OVER(ORDER BY Salary DESC) AS RANK_BY_SALARY
FROM employeesalary

-- 2) WITH PARTITION BY

SELECT JOBTITLE, SALARY,
DENSE_RANK() OVER(PARTITION BY JOBTITLE ORDER BY Salary DESC) AS RANK_BY_SALARY
FROM employeesalary



 